version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
        - ./db/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: 2107
      POSTGRES_USER: root
      POSTGRES_DB: rest-to-graphql
volumes:
  postgres:
    